import type { Metadata } from "next";
import "./globals.css";
import Root from "@/components/root";
import Header from "@/components/header";
import { ThemeContextProvider } from "@/contexts/ThemeContext";

export const metadata: Metadata = {
    title: "Huntize",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <ThemeContextProvider>
                <Root>
                    <Header />
                </Root>
            </ThemeContextProvider>
        </html>
    );
}
