import type { Metadata } from "next";
import "./globals.css";
import Home from "./page";

export const metadata: Metadata = {
    title: "Huntize",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="theme" suppressHydrationWarning>
            <head>
                <script id="vb" src="/noflash.js"></script>
            </head>
            {children}
        </html>
    );
}
