import type { Metadata } from "next";
import "./globals.css";
import Root from "@/components/root";
import Header from "@/components/header";

export const metadata: Metadata = {
    title: "Huntize",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <Root>
                <Header />
            </Root>
        </html>
    );
}
